/**
 * BASE PAGE — Reusable UI Interaction Methods & Result Collection
 * Base class for all page objects (CreateSalesorderPage, TestPOVoyagePage, etc).
 * Provides safe element interactions, D365-specific helpers (waitForProcessing,
 * date formatting, lookup handling), and auto-collection of test results.
 *
 * Changes (production fixes applied):
 *  Fix #2 — safeClick: removed redundant waitFor() before click() — race condition
 *  Fix #3 — safeFill: lookup timeouts now env-driven, waitForLookupOptionsStable()
 *            added before scanning options, waitForProcessing() after option click
 *  Fix #4 — captureText: added this.ELEMENT_TIMEOUT + .trim() (was inconsistent)
 *            captureTextWithRetry: NEW method — was generated by converter but missing here
 *  Fix #6 — captureInputValueWithRetry: replaced fixed-sleep polling with
 *            Playwright-native waitForFunction (efficient ~100ms internal polling)
 *  Fix #7 — waitForD365GridLoad: NEW method — waits for grid rows after list page nav
 */
import { Page, BrowserContext, Locator, expect } from "@playwright/test";
import * as dotenv from "dotenv";

dotenv.config({ quiet: true });

export class BasePage {
  readonly page: Page;
  readonly context: BrowserContext;
  readonly D365_URL = process.env.D365_URL ?? "";
  readonly ELEMENT_TIMEOUT = parseInt(process.env.D365_ELEMENT_TIMEOUT ?? "60000");

  // ─── Lookup/combobox server-call timeout ───────────────────────────────────
  // D365 fires an OData/REST call for every lookup field. On loaded UAT/Prod
  // instances this takes 2-8 seconds. 5000ms default is safe for most installs.
  // Override via .env: D365_LOOKUP_TIMEOUT=8000
  readonly LOOKUP_TIMEOUT = parseInt(process.env.D365_LOOKUP_TIMEOUT ?? "5000");

  // ─── Nav search results timeout ────────────────────────────────────────────
  // Navigation search overlay fires a separate query. Slightly more room than
  // a regular combobox since it searches the full module tree.
  // Override via .env: D365_NAV_SEARCH_TIMEOUT=6000
  readonly NAV_SEARCH_TIMEOUT = parseInt(process.env.D365_NAV_SEARCH_TIMEOUT ?? "4000");

  // ─── Lookup probe — fast detection window ─────────────────────────────────
  // How long to wait to detect if ANY dropdown started appearing after fill().
  // Plain text fields never show a dropdown — this is the max overhead for them.
  // Override via .env: D365_LOOKUP_PROBE_MS=1500
  readonly LOOKUP_PROBE_MS = parseInt(process.env.D365_LOOKUP_PROBE_MS ?? "1000");

  // ─── result collector — auto collects all created data during test ─────────
  protected collectedResults: Record<string, string | number | boolean | null> = {};

  constructor(page: Page, context: BrowserContext) {
    this.page = page;
    this.context = context;
  }

  // ─── reset collector — called by fixture at start of every test ───────────
  resetCollectedResults(): void {
    this.collectedResults = {};
  }

  // ─── get all collected results — called by fixture at end of test ─────────
  getCollectedResults(): Record<string, string | number | boolean | null> {
    return { ...this.collectedResults };
  }

  // ─── capture input field value and auto register ──────────────────────────
  // D365 fields resolve to an outer div wrapper. locator.inputValue() requires
  // an actual <input>/<textarea>/<select>. Try the locator directly first;
  // if that fails (because it's a div wrapper), look for the inner <input>.
  // Final fallback: textContent (for read-only display fields).
  // Uses state:"attached" not state:"visible" — D365 header fields are often
  // scrolled out of viewport so visibility check times out. scrollIntoViewIfNeeded
  // ensures the element is in view before reading the value.
  async captureInputValue(
    key: string,
    locator: Locator
  ): Promise<string> {
    await locator.waitFor({ state: "attached", timeout: this.ELEMENT_TIMEOUT });
    await locator.scrollIntoViewIfNeeded().catch(() => {});
    let value: string;
    try {
      value = await locator.inputValue();
    } catch {
      // locator is an outer div — look for inner input
      const inner = locator.locator("input").first();
      if ((await inner.count()) > 0) {
        value = await inner.inputValue();
      } else {
        // last resort: read text content (display-only fields)
        value = (await locator.textContent())?.trim() ?? "";
      }
    }
    if (!value) throw new Error(`❌ captureInputValue: [${key}] is empty`);
    this.collectedResults[key] = value;
    console.log(`📋 Captured [${key}]: ${value}`);
    return value;
  }

  // ─── capture input value with retry — for D365 auto-generated fields ──────
  // D365 fields like SO number, PO number, voucher number take 1-3 seconds to
  // populate after save/OK. captureInputValue() reads once and throws if empty.
  //
  // FIX #6 — replaced fixed-sleep polling (waitForTimeout) with Playwright-native
  // waitForFunction which polls every ~100ms internally. Most D365 fields populate
  // within 100-300ms after save — the old approach wasted up to 5s per field.
  // The attempt loop is kept as a safety net for the read phase.
  async captureInputValueWithRetry(
    key: string,
    locator: Locator,
    maxAttempts: number = 5,
    intervalMs: number = 1000
  ): Promise<string> {
    // ── Phase 1: efficient poll until element has a non-empty value ───────────
    // Total budget = maxAttempts × intervalMs (default 5s).
    // waitForFunction polls ~100ms internally — far faster than fixed sleeps.
    const totalTimeout = maxAttempts * intervalMs;
    try {
      await locator.waitFor({ state: "attached", timeout: this.ELEMENT_TIMEOUT });
      await locator.scrollIntoViewIfNeeded().catch(() => {});

      await this.page.waitForFunction(
        ({ selector }: { selector: string }) => {
          const el = document.querySelector(selector) as HTMLInputElement | null;
          if (!el) return false;
          // check inputValue (real inputs)
          if (el.value?.trim()) return true;
          // check textContent (display-only)
          if (el.textContent?.trim()) return true;
          return false;
        },
        { selector: await locator.evaluate((el: Element) => {
            // build a minimal selector from the element's own attributes
            if (el.id) return `#${CSS.escape(el.id)}`;
            const ctrl = el.getAttribute('data-dyn-controlname')
              || el.closest('[data-dyn-controlname]')?.getAttribute('data-dyn-controlname');
            if (ctrl) return `[data-dyn-controlname="${ctrl}"] input, [data-dyn-controlname="${ctrl}"]`;
            return el.tagName.toLowerCase();
          }).catch(() => 'input')
        },
        { timeout: totalTimeout }
      ).catch(() => {
        // field did not populate within budget — fall through to attempt loop
      });
    } catch {
      // waitFor itself timed out — fall through to attempt loop for clear error
    }

    // ── Phase 2: read the value — should be populated now ────────────────────
    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      try {
        const value = await this.captureInputValue(key, locator);
        if (value) return value;
      } catch (err: any) {
        // Page closed mid-retry (test timeout fired while waiting) — return
        // empty string immediately. The test will fail fast with a clear message
        // rather than hanging for the full retry budget then throwing a cryptic
        // "Target page, context or browser has been closed" error.
        if (err?.message?.includes('Target page') || err?.message?.includes('context or browser')) {
          console.warn(`⚠️  captureInputValueWithRetry: [${key}] — page closed during retry, returning empty`);
          this.collectedResults[key] = '';
          return '';
        }
        // not ready yet — continue retrying
      }
      if (attempt < maxAttempts) {
        console.log(`⏳ captureInputValueWithRetry: [${key}] attempt ${attempt}/${maxAttempts}`);
        try {
          await this.page.waitForTimeout(intervalMs);
        } catch {
          // Page closed while sleeping — exit immediately
          console.warn(`⚠️  captureInputValueWithRetry: [${key}] — page closed during wait, returning empty`);
          this.collectedResults[key] = '';
          return '';
        }
      }
    }
    throw new Error(`❌ captureInputValueWithRetry: [${key}] was empty after ${maxAttempts} attempts`);
  }

  // ─── capture text content and auto register ───────────────────────────────
  // FIX #4 — added this.ELEMENT_TIMEOUT (was using Playwright 30s default
  // inconsistently with the rest of the class) and added .trim() on value.
  async captureText(
    key: string,
    locator: Locator
  ): Promise<string> {
    await locator.waitFor({ state: "visible", timeout: this.ELEMENT_TIMEOUT });
    const value = (await locator.textContent())?.trim() ?? "";
    if (!value) throw new Error(`❌ captureText: [${key}] is empty`);
    this.collectedResults[key] = value;
    console.log(`📋 Captured [${key}]: ${value}`);
    return value;
  }

  // ─── capture text with retry — for D365 display fields that populate after save
  // FIX #4 — NEW method. converter.ts generates calls to captureTextWithRetry()
  // for display-only captured elements but it did not exist in BasePage —
  // caused TypeError at runtime in every generated Page Object with captured fields.
  //
  // D365 fields like document title, status label, header text take 1-3 seconds
  // to render after a save/confirm. This method polls until the element has
  // real text content. Mirrors captureInputValueWithRetry for read-only elements.
  async captureTextWithRetry(
    key: string,
    locator: Locator,
    maxAttempts: number = 5,
    intervalMs: number = 1000
  ): Promise<string> {
    // ── Phase 1: efficient poll until element has non-empty text content ──────
    // waitForFunction polls ~100ms internally — far faster than fixed sleeps.
    // Most D365 display fields (titles, status labels) populate within 100-500ms
    // after save. The old fixed-sleep approach wasted up to 5s per field.
    // Total budget = maxAttempts × intervalMs (default 5s) — same as before.
    const totalTimeout = maxAttempts * intervalMs;
    try {
      await locator.waitFor({ state: "attached", timeout: this.ELEMENT_TIMEOUT });
      await locator.scrollIntoViewIfNeeded().catch(() => {});

      // Build a minimal selector from the element's own attributes so we can
      // pass it into waitForFunction (Locator objects cannot cross the JS boundary).
      const selector = await locator.evaluate((el: Element) => {
        if (el.id) return `#${CSS.escape(el.id)}`;
        const ctrl = el.getAttribute('data-dyn-controlname')
          || el.closest('[data-dyn-controlname]')?.getAttribute('data-dyn-controlname');
        if (ctrl) return `[data-dyn-controlname="${ctrl}"]`;
        // fallback: use tag + aria-label if present
        const label = el.getAttribute('aria-label');
        if (label) return `${el.tagName.toLowerCase()}[aria-label="${label}"]`;
        return el.tagName.toLowerCase();
      }).catch(() => '[data-dyn-role]');

      await this.page.waitForFunction(
        (sel: string) => {
          const el = document.querySelector(sel);
          return !!(el && (el.textContent ?? '').trim());
        },
        selector,
        { timeout: totalTimeout }
      ).catch(() => {
        // element did not populate within budget — fall through to attempt loop
      });
    } catch {
      // waitFor itself timed out — fall through to attempt loop for clear error
    }

    // ── Phase 2: read the value — should be populated now ────────────────────
    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      try {
        await locator.waitFor({ state: "visible", timeout: this.ELEMENT_TIMEOUT });
        const value = (await locator.textContent())?.trim() ?? "";
        if (value) {
          this.collectedResults[key] = value;
          console.log(`📋 Captured [${key}]: ${value}`);
          return value;
        }
      } catch (err: any) {
        // Page closed mid-retry — return empty immediately
        if (err?.message?.includes('Target page') || err?.message?.includes('context or browser')) {
          console.warn(`⚠️  captureTextWithRetry: [${key}] — page closed during retry, returning empty`);
          this.collectedResults[key] = '';
          return '';
        }
        // not ready yet — continue retrying
      }
      if (attempt < maxAttempts) {
        console.log(`⏳ captureTextWithRetry: [${key}] attempt ${attempt}/${maxAttempts}`);
        try {
          await this.page.waitForTimeout(intervalMs);
        } catch {
          console.warn(`⚠️  captureTextWithRetry: [${key}] — page closed during wait, returning empty`);
          this.collectedResults[key] = '';
          return '';
        }
      }
    }
    throw new Error(`❌ captureTextWithRetry: [${key}] was empty after ${maxAttempts} attempts`);
  }

  // ─── capture any manual value and auto register ───────────────────────────
  captureResult(
    key: string,
    value: string | number | boolean | null
  ): void {
    this.collectedResults[key] = value;
    console.log(`📋 Captured [${key}]: ${value}`);
  }

  // ─── navigate to base d365 url ────────────────────────────────────────────
  async navigateToBase(): Promise<void> {
    await this.page.goto(this.D365_URL, {
      waitUntil: "domcontentloaded",
      timeout: 60000,
    });
  }

  // ─── wait for page to be fully loaded ─────────────────────────────────────
  // NOTE: D365 never reaches networkidle due to constant background polling.
  // Prefer waitForProcessing() for D365 flows. This method kept for compatibility.
  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState("networkidle");
  }

  // ─── wait for D365 processing indicators to clear ─────────────────────────
  // Checks .processing, .loading-indicator, #ShellBlockingDiv (full-page overlays only).
  // [aria-busy="true"] intentionally excluded — D365 sets it permanently on grids/nav.
  // Capped at 15s — D365 background polling means networkidle is never reached.
  async waitForProcessing(timeout: number = 30000): Promise<void> {
    const effectiveTimeout = timeout;
    await this.page.waitForFunction(() => {
      // ⚠️  DO NOT include [aria-busy="true"] here.
      // D365 permanently sets aria-busy on grids, nav panes, activity centers —
      // these never clear and cause every waitForProcessing call to hit the timeout.
      // Only check actual full-page blocking overlays that D365 puts up during server ops.
      const selectors = [".processing", ".loading-indicator", "#ShellBlockingDiv"];

      // Helper: checks if an element is actually visible on screen.
      // D365 keeps #ShellBlockingDiv and .processing in the DOM at all times —
      // we must check computed style, not just DOM presence, to avoid false positives.
      function isVisible(el: Element): boolean {
        const style = (el as HTMLElement).style;
        const computed = window.getComputedStyle(el);
        if (style.display === "none" || computed.display === "none") return false;
        if (style.visibility === "hidden" || computed.visibility === "hidden") return false;
        if ((el as HTMLElement).hidden) return false;
        if (computed.opacity === "0") return false;
        return true;
      }

      // check main frame — only count VISIBLE instances
      for (const selector of selectors) {
        const els = Array.from(document.querySelectorAll(selector));
        if (els.some(isVisible)) return false;
      }

      // check all iframes — D365 renders spinners/blockers inside iframes
      const frames = Array.from(document.querySelectorAll("iframe"));
      for (const frame of frames) {
        try {
          const doc = frame.contentDocument;
          if (!doc) continue;
          for (const selector of selectors) {
            const els = Array.from(doc.querySelectorAll(selector));
            if (els.some(isVisible)) return false;
          }
        } catch {
          continue;
        }
      }

      return true;
    }, { timeout: effectiveTimeout }).catch(() => {
      console.warn(`waitForProcessing: indicators did not clear within ${effectiveTimeout}ms, continuing`);
    });
  }

  // ─── date helpers ─────────────────────────────────────────────────────────

  /**
   * Returns today's date in MM/DD/YYYY format (US format).
   * e.g. "03/18/2026"
   */
  getTodayFormatted(): string {
    const d = new Date();
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${m}/${day}/${y}`;
  }

  /**
   * Resolves a date value for form filling:
   * - If Excel data has a non-empty value for this key → use it (manual override)
   * - Otherwise → use today's date automatically
   *
   * Usage: await this.safeFill(this.rangeValue, this.resolveDateValue(data, "rangeValue"));
   */
  resolveDateValue(data: Record<string, string>, key: string): string {
    const excelValue = data[key]?.trim();
    return excelValue || this.getTodayFormatted();
  }

  // ─── soft assertions — log failure but never stop the test ──────────────
  // Use for post-creation verifications where the locator might vary by D365
  // config (e.g. PO number, vendor name visible after save).
  // Hard asserts (expect) remain for critical gates — dialogs, buttons, errors.
  //
  // IMPORTANT: must use regular expect() inside try/catch — NOT expect.soft().
  // expect.soft() does not throw; Playwright tracks failures internally and
  // marks the test FAILED at the end regardless of any surrounding try/catch.
  // Regular expect() throws immediately → catch handles it → test truly continues.
  async softAssertVisible(key: string, locator: Locator): Promise<void> {
    try {
      await expect(locator).toBeVisible({ timeout: 10000 });
      console.log(`✅ SoftAssert [${key}]: visible`);
    } catch {
      console.warn(`⚠️  SoftAssert [${key}]: NOT visible — continuing`);
    }
  }

  async softAssertText(key: string, locator: Locator, expected: string): Promise<void> {
    try {
      await expect(locator).toContainText(expected, { timeout: 10000 });
      console.log(`✅ SoftAssert [${key}]: contains "${expected}"`);
    } catch {
      console.warn(`⚠️  SoftAssert [${key}]: text mismatch — test continues`);
    }
  }

  // ─── wait for D365 app to fully load — central implementation ────────────
  // Uses domcontentloaded + app shell element detection.
  // D365 has constant background network polling so networkidle is never reached —
  // this approach waits for the actual app UI to be present instead.
  // Falls through gracefully if app shell not found (e.g. login/MFA page).
  async isLoaded(): Promise<boolean> {
    try {
      await this.page.waitForLoadState("domcontentloaded", { timeout: 60000 });

      // ─── Phase 1: detect if we landed on a login/MFA page ───────────────
      // D365 session expiry mid-run silently redirects to login.
      // If detected: log a clear warning and wait up to D365_AUTH_TIMEOUT_MS
      // (default 120s) for the team to complete MFA manually.
      // Override via .env: D365_AUTH_TIMEOUT_MS=180000 for slow SSO providers.
      const loginPatterns = [
        'login.microsoftonline.com',
        'login.live.com',
        '/adfs/',
        'microsoftonline.com/common',
        'oauth2/authorize',
      ];
      const currentUrl = this.page.url();
      const isOnLogin = loginPatterns.some(p => currentUrl.includes(p));

      if (isOnLogin) {
        console.warn('⚠️  isLoaded: detected login/MFA page — auth state may have expired');
        console.warn('   Waiting for manual MFA completion...');
        const authTimeout = parseInt(process.env.D365_AUTH_TIMEOUT_MS ?? '120000');

        await this.page.waitForFunction(
          (patterns: string[]) => !patterns.some(p => window.location.href.includes(p)),
          loginPatterns,
          { timeout: authTimeout }
        ).catch(() => {
          console.warn('⚠️  isLoaded: still on login page after timeout — test will likely fail');
        });

        // after MFA completes D365 needs extra time to redirect and boot
        await this.page.waitForLoadState("domcontentloaded", { timeout: 60000 }).catch(() => {});
      }

      // ─── Phase 2: poll for D365 shell ────────────────────────────────────
      // waitForFunction exits as soon as any shell selector appears — no fixed
      // sleep. Default 8000ms covers slow UAT/Prod post-login loads.
      // Override via .env: D365_BOOT_TIMEOUT_MS=12000 for very slow instances.
      const bootTimeout = parseInt(process.env.D365_BOOT_TIMEOUT_MS ?? '8000');

      await this.page.waitForFunction(() => {
        return !!(
          document.querySelector('[data-dyn-controlname="NavPaneToggle"]') ||
          document.querySelector('[data-dyn-role="Application"]') ||
          document.querySelector('[data-dyn-role="MessageProcessor"]') ||
          document.querySelector('[data-dyn-controlname="NavigationSearchBox"]') ||
          document.querySelector('.dyn-header-container')
        );
      }, { timeout: bootTimeout }).catch(() => {
        console.warn(`isLoaded: D365 shell not detected within ${bootTimeout}ms — continuing`);
      });

      // ─── Phase 3: wait for any loading overlays to clear ─────────────────
      // After shell appears D365 still runs background OData calls that block
      // the UI with .processing / #ShellBlockingDiv for 2-5 seconds.
      // waitForProcessing uses a short cap here — we only want to catch the
      // initial load blocker, not wait forever on background polling.
      await this.waitForProcessing(parseInt(process.env.D365_INITIAL_LOAD_TIMEOUT_MS ?? '10000'));

      return true;
    } catch (error) {
      console.warn("isLoaded: load timeout, continuing");
      return false;
    }
  }

  // ─── waitForD365GridLoad ───────────────────────────────────────────────────
  // FIX #7 — NEW method.
  // After navigating to a D365 list page (All Sales Orders, All POs, All Customers
  // etc.) D365 fires a background OData call to populate the grid rows.
  // isLoaded() only waits for the page shell — NOT for the grid data rows.
  // Without this, the first grid interaction (click row, apply filter) fires
  // while the grid is still loading → element not found / not interactable errors.
  //
  // Strategy — purely structural ARIA detection, no hardcoded selectors:
  //   1. Wait for grid container (role="grid" or role="treegrid") to be attached
  //   2. Wait for at least one data row inside the grid to appear
  //   3. Wait for processing indicators to clear (spinner/blocker)
  //
  // Call after isLoaded() whenever navigating to any list/grid page.
  // Non-fatal — if grid does not load within timeout, logs warning and continues.
  // The next interaction will surface the real error clearly.
  async waitForD365GridLoad(timeout?: number): Promise<void> {
    const effectiveTimeout = timeout ?? this.ELEMENT_TIMEOUT;

    try {
      // Step 1 — wait for the grid container to be present in DOM
      await this.page.waitForSelector(
        '[role="grid"], [role="treegrid"]',
        { state: "attached", timeout: effectiveTimeout }
      );

      // Step 2 — wait for at least one data row inside the grid.
      // D365 renders an empty grid shell first, rows arrive after OData responds.
      // waitForFunction polls ~100ms internally — efficient, no fixed sleep.
      await this.page.waitForFunction(() => {
        const grid = document.querySelector('[role="grid"], [role="treegrid"]');
        if (!grid) return false;
        // Exclude header rows — they contain columnheader cells
        const rows = Array.from(grid.querySelectorAll('[role="row"]'));
        const dataRows = rows.filter(r =>
          !r.querySelector('[role="columnheader"]') &&
          !r.querySelector('[role="rowheader"]')
        );
        return dataRows.length > 0;
      }, { timeout: effectiveTimeout }).catch(() => {
        console.warn('⚠️  waitForD365GridLoad: no data rows appeared — grid may be empty or still loading');
      });

      // Step 3 — wait for any processing spinner/blocker to clear
      await this.waitForProcessing();

      console.log('✅ D365 grid loaded and ready');
    } catch {
      console.warn('⚠️  waitForD365GridLoad: timed out — continuing anyway');
    }
  }

  // ─── ensure D365 nav rail is expanded before clicking nav items ───────────
  // The nav rail starts collapsed on dashboard. It expands on hover which the
  // recorder cannot capture. This method checks and clicks the toggle if needed.
  // Called automatically by every generated navigateTo{Flow}() method.
  async ensureNavExpanded(): Promise<void> {
    try {
      const toggle = this.page.locator(
        `[data-dyn-controlname="NavPaneToggle"], ` +
        `[data-dyn-title="Expand the navigation pane"], ` +
        `button[aria-label="Expand the navigation pane"], ` +
        `button[aria-label="Navigation pane"]`
      );

      const isToggleVisible = await this.isVisible(toggle);
      if (!isToggleVisible) return; // already expanded or not a collapsible nav

      await toggle.click();
      await this.page.waitForTimeout(500); // allow D365 nav expand CSS animation (~300ms) to settle
      await this.waitForProcessing();
      console.log("🔽 Nav rail expanded");
    } catch {
      // nav may already be expanded — non-fatal, continue
    }
  }

  // ─── safe click ───────────────────────────────────────────────────────────
  // FIX #2 — removed redundant waitFor({ state: 'visible' }) before click().
  // locator.click() already auto-waits internally for: attached, visible,
  // stable, not obscured, enabled. The previous waitFor() + click() pattern
  // created a race window where D365 could collapse a FastTab or render a
  // spinner between the two calls → click() found element no longer actionable
  // even though waitFor() passed 1ms earlier. One call is correct and safe.
  async safeClick(locator: Locator): Promise<void> {
    await locator.click({ timeout: this.ELEMENT_TIMEOUT });
  }

  // ─── navSearch ────────────────────────────────────────────────────────────
  // Reusable D365 global search helper. Opens the search bar, types the query
  // character-by-character (so D365's keyup debounce fires), waits for the
  // result item to become visible, then clicks it — all atomically in one call.
  //
  // MUST stay atomic: the D365 nav overlay is focus-sensitive and closes on
  // any blur event. Never split fill and click across separate spec steps.
  //
  // Usage in any Page class:
  //   async navigateToMyPage(): Promise<void> {
  //     await this.navSearch('my page name', this.myPageLocator);
  //   }
  async navSearch(searchText: string, resultLocator: Locator): Promise<void> {
    const searchBtn = this.page.locator('button[aria-label="Search"]');
    const searchBox = this.page.locator('input[aria-label="Search for a page"]');
    await searchBtn.waitFor({ state: 'visible', timeout: this.ELEMENT_TIMEOUT });
    await searchBtn.click();
    await searchBox.waitFor({ state: 'visible', timeout: 10000 });
    await searchBox.pressSequentially(searchText, { delay: 100 });
    await resultLocator.first().waitFor({ state: 'visible', timeout: this.ELEMENT_TIMEOUT });
    await resultLocator.first().click();
    await this.waitForProcessing();
    await this.page.waitForLoadState('domcontentloaded');
  }

  // ─── safe fill ────────────────────────────────────────────────────────────
  // D365 fields are structured as:
  //   <div data-dyn-controlname="FieldName">   ← what the locator resolves to
  //     <input type="text" />                 ← actual fillable element
  //   </div>
  // locator.clear() / locator.fill() fail on the div wrapper.
  // Fix: click the container to activate the D365 control, then fill the inner
  // <input> or [contenteditable] child. Falls back to direct fill if no inner
  // input found (some D365 controls are contenteditable on the container itself).
  //
  // Handles three real-world fill scenarios robustly:
  //
  // 1. NAVIGATION SEARCH BOX
  //    Type → D365 shows navigation results (a site-level overlay with links).
  //    We leave it open. The next recorded safeClick() selects the nav item.
  //    Auto-clicking here would navigate the page and break subsequent steps.
  //
  // 2. LOOKUP / COMBOBOX with [role="listbox"] options
  //    Type → D365 fetches matching records via OData → [role="listbox"] appears.
  //    We wait for options to stabilise (D365 renders "Loading..." first, real
  //    records arrive after the server responds — scanning before stable = misses).
  //    We find the option whose text best matches the typed value and click it.
  //    waitForProcessing() after click waits for D365 linked field auto-population
  //    (e.g. Customer → Currency, Payment Terms, Delivery Address auto-fill).
  //
  // 3. PLAIN TEXT FIELD (no dropdown appears)
  //    Type → Tab to confirm the field and move focus.
  //
  // Detection is purely structural (ARIA roles + D365-specific container names).
  // No field names, no selectors for specific controls — works across all platforms.
  // All timeouts are env-driven — no hardcoded values.
  async safeFill(locator: Locator, value: string): Promise<void> {
    // ── 1. Activate the field ────────────────────────────────────────────────
    await locator.click({ timeout: this.ELEMENT_TIMEOUT });

    // ── 2. Resolve the actual fillable element inside the D365 div wrapper ───
    // D365 wraps every input in a div container — fill() on the div fails.
    const inner = locator.locator('input, [contenteditable="true"]').first();
    const fillTarget = (await inner.count()) > 0 ? inner : locator;

    // ── 3. Wait for enabled — D365 greys out fields during page transitions ──
    await expect(fillTarget).toBeEnabled({ timeout: this.ELEMENT_TIMEOUT });

    // ── 4. Type the value ────────────────────────────────────────────────────
    await fillTarget.fill(value);

    // ── 5. Fast probe — did ANY dropdown start appearing? ────────────────────
    // LOOKUP_PROBE_MS (default 1000ms) detects if D365 fired a lookup/nav call.
    // Plain text fields never show a dropdown → falls through to Tab immediately.
    // Lookup fields: D365 renders the container within 200-500ms of fill even
    // before the server responds — detected here, then we wait properly below.
    const navLocator   = this.page.locator('[data-dyn-controlname="NavigationSearchResults"]');
    const comboLocator = this.page.locator('[role="listbox"]');

    const [navStarted, comboStarted] = await Promise.all([
      navLocator.first()
        .waitFor({ state: 'visible', timeout: this.LOOKUP_PROBE_MS })
        .then(() => true).catch(() => false),
      comboLocator.first()
        .waitFor({ state: 'visible', timeout: this.LOOKUP_PROBE_MS })
        .then(() => true).catch(() => false),
    ]);

    // ── 6a. Nav search overlay appeared ─────────────────────────────────────
    // Nav results are a site-level overlay. Leave open — the next recorded
    // safeClick() selects the nav item. Do NOT click here — would navigate
    // away and break subsequent steps that were recorded after this fill.
    //
    // IMPORTANT: Do NOT add any waits here. The nav overlay is focus-sensitive
    // and closes on blur. The Page method that calls safeFill() is responsible
    // for doing fill + click atomically in the same function body (no async gap).
    // See Test8Page.navigateToTest8() and Test20Page.fillSearchBox() for the
    // correct atomic pattern. Any wait here risks the overlay closing.
    if (navStarted) return;

    // ── 6b. Lookup / combobox dropdown appeared ──────────────────────────────
    if (comboStarted) {
      // Wait for real options before scanning for text match.
      // D365 renders an empty listbox or "Loading..." placeholder first.
      // Real records arrive after the OData server call completes (2-8s).
      // Scanning before stable = options.count() is 0 or 1 (Loading) → misses.
      await this.waitForLookupOptionsStable();

      const options = this.page.locator('[role="listbox"] [role="option"], [role="option"]');
      const count   = await options.count();
      let clicked   = false;
      const needle  = value.toLowerCase().trim();

      // Pass 1 — exact or starts-with match (most confident)
      for (let i = 0; i < count; i++) {
        const opt  = options.nth(i);
        const text = ((await opt.textContent()) ?? '').toLowerCase().trim();
        if (text === needle || text.startsWith(needle)) {
          await opt.click({ timeout: this.ELEMENT_TIMEOUT });
          clicked = true;
          break;
        }
      }

      // Pass 2 — contains match (e.g. typed "10002", option is "10002 - Vendor Name")
      if (!clicked) {
        for (let i = 0; i < count; i++) {
          const opt  = options.nth(i);
          const text = ((await opt.textContent()) ?? '').toLowerCase().trim();
          if (text.includes(needle)) {
            await opt.click({ timeout: this.ELEMENT_TIMEOUT });
            clicked = true;
            break;
          }
        }
      }

      // Pass 3 — no text match, Tab accepts D365's first resolved result
      if (!clicked) await fillTarget.press('Tab');

      // CRITICAL — wait for D365 linked field auto-population after selection.
      // Selecting Customer → D365 auto-fills Currency, Payment Terms, Tax Group,
      // Delivery Address (all via separate background OData calls).
      // Without this the next safeFill starts while D365 is still resolving
      // → next field gets disabled, overwritten, or silently ignored.
      await this.waitForProcessing();
      return;
    }

    // ── 6c. Plain text field — no dropdown appeared ──────────────────────────
    // Tab confirms the field value and moves focus to the next field.
    await fillTarget.press('Tab');
  }

  // ─── waitForLookupOptionsStable (private) ─────────────────────────────────
  // Waits until the listbox contains at least one option with real text content.
  // D365 renders a "Loading..." placeholder before real records arrive from OData.
  // Uses waitForFunction — polls ~100ms internally, no fixed sleep overhead.
  // Non-fatal — if options don't stabilise within LOOKUP_TIMEOUT, proceeds anyway.
  // The subsequent click passes will find 0 options and fall through to Tab.
  protected async waitForLookupOptionsStable(): Promise<void> {
    await this.page.waitForFunction(() => {
      const options = document.querySelectorAll('[role="listbox"] [role="option"]');
      if (options.length === 0) return false;
      for (const opt of Array.from(options)) {
        const text = (opt.textContent ?? '').trim().toLowerCase();
        if (text && text !== 'loading...' && text !== 'loading') return true;
      }
      return false;
    }, { timeout: this.LOOKUP_TIMEOUT }).catch(() => {
      console.warn('⚠️  waitForLookupOptionsStable: options did not stabilise within timeout — proceeding');
    });
  }

  // ─── safe select dropdown ──────────────────────────────────────────────────
  // Same outer div wrapper issue — find inner <select> child to call selectOption.
  async safeSelect(locator: Locator, value: string): Promise<void> {
    await locator.click({ timeout: this.ELEMENT_TIMEOUT });
    const inner = locator.locator("select").first();
    const hasInner = (await inner.count()) > 0;
    if (hasInner) {
      await inner.selectOption(value);
    } else {
      await locator.selectOption(value);
    }
  }

  // ─── get text from element ─────────────────────────────────────────────────
  async getText(locator: Locator): Promise<string> {
    await locator.waitFor({ state: "visible", timeout: this.ELEMENT_TIMEOUT });
    return (await locator.textContent()) ?? "";
  }

  // ─── validate and format date to D365 environment format ──────────────────
  // Accepts both US format (M/D/YYYY or MM/DD/YYYY) and ISO (YYYY-MM-DD).
  // D365_DATE_FORMAT in .env controls output format (default MM/DD/YYYY):
  //   MM/DD/YYYY → 03/18/2026  (US)
  //   DD/MM/YYYY → 18/03/2026  (UK)
  //   YYYY-MM-DD → 2026-03-18  (ISO)
  // Also accepts the keyword TODAY (resolved to today's date).
  validateAndFormatDate(key: string, value: string): string {
    // ─── handle TODAY keyword ──────────────────────────────────────────────
    if (value.trim().toUpperCase() === 'TODAY') {
      return this.validateAndFormatDate(key, this.getTodayFormatted());
    }

    let year: string, month: string, day: string;

    // ─── US format: M/D/YYYY or MM/DD/YYYY e.g. 3/18/2026 or 03/18/2026 ──
    const usRegex = /^(\d{1,2})\/(\d{1,2})\/(\d{4})$/;
    const usMatch = value.trim().match(usRegex);

    // ─── ISO format: YYYY-MM-DD e.g. 2026-03-18 ───────────────────────────
    const isoRegex = /^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/;
    const isoMatch = value.trim().match(isoRegex);

    if (usMatch) {
      month = usMatch[1].padStart(2, '0');
      day   = usMatch[2].padStart(2, '0');
      year  = usMatch[3];
    } else if (isoMatch) {
      year  = isoMatch[1];
      month = isoMatch[2];
      day   = isoMatch[3];
    } else {
      throw new Error(
        `❌ [${key}] invalid date: "${value}" — use MM/DD/YYYY (e.g. 03/18/2026), YYYY-MM-DD (e.g. 2026-03-18), or the word TODAY`
      );
    }

    const format = process.env.D365_DATE_FORMAT ?? "MM/DD/YYYY";

    switch (format.toUpperCase()) {
      case "MM/DD/YYYY": return `${month}/${day}/${year}`;
      case "DD/MM/YYYY": return `${day}/${month}/${year}`;
      case "YYYY-MM-DD": return `${year}-${month}-${day}`;
      case "MM-DD-YYYY": return `${month}-${day}-${year}`;
      case "DD-MM-YYYY": return `${day}-${month}-${year}`;
      default:
        throw new Error(
          `❌ D365_DATE_FORMAT "${format}" not supported — use MM/DD/YYYY, DD/MM/YYYY, YYYY-MM-DD, MM-DD-YYYY or DD-MM-YYYY`
        );
    }
  }

  // ─── check if element is visible ──────────────────────────────────────────
  async isVisible(locator: Locator): Promise<boolean> {
    try {
      await locator.waitFor({ state: "visible", timeout: 5000 });
      return true;
    } catch {
      return false;
    }
  }

  // ─── check for D365 error banners (non-throwing) ──────────────────────────
  // D365 surfaces errors through several UI patterns (message bars, alert roles,
  // validation highlights). This method scans all known selectors and logs any
  // visible error text. It does NOT throw — call at the end of a test step for
  // diagnostics. Returns { hasErrors, errors[] } for optional assertion.
  async checkForD365Errors(): Promise<{ hasErrors: boolean; errors: string[] }> {
    if (this.page.isClosed()) return { hasErrors: false, errors: [] };
    const errorSelectors = [
      '.message-bar.message-error',
      '[role="alert"][aria-live="assertive"]',
      '.error-message',
      '[data-dyn-role="ErrorMessage"]',
      '.validation-error',
      '[data-dyn-role="MessageBar"][data-dyn-messagetype="Error"]',
    ];
    const errors: string[] = [];
    for (const sel of errorSelectors) {
      const elements = await this.page.locator(sel).all();
      for (const el of elements) {
        const visible = await el.isVisible().catch(() => false);
        if (visible) {
          const text = (await el.textContent())?.trim();
          if (text) errors.push(text);
        }
      }
    }
    if (errors.length > 0) {
      console.warn(`⚠️ D365 errors detected:\n  - ${errors.join('\n  - ')}`);
    }
    return { hasErrors: errors.length > 0, errors };
  }
}