import { Page, Locator, expect } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * PODchannelPage -- Auto-generated by Smart Recorder v3.0
 * Platform: D365 | Flow: PO_D_channel
 * Generated: 2026-03-12T20:28:58.199Z
 * Session: sessions/podchannel_session.json
 *
 * To regenerate: npx ts-node converter.ts sessions/podchannel_session.json
 * To edit & regenerate: npx ts-node converter.ts sessions/podchannel_session.json --edit
 */
export class PODchannelPage extends BasePage {

  constructor(page: Page) {
    super(page, page.context());
  }

  // --- locators -------------------------------------------------------------------
  readonly search: Locator = this.page.locator(`button[aria-label="Search"]`);
  readonly searchBox: Locator = this.page.locator(`input[aria-label="Search for a page"]`);
  readonly allSalesOrders: Locator = this.page.locator(`span:has-text("All sales orders")`);
  readonly newButton: Locator = this.page.locator(`[data-dyn-controlname="SystemDefinedNewButton"][name="SystemDefinedNewButton"]`);
  readonly custAccount: Locator = this.page.locator(`[data-dyn-controlname="SalesTable_CustAccount"]`);
  readonly rsmDelayPayment: Locator = this.page.locator(`[data-dyn-controlname="SalesTable_rsmDelayPayment"]`);
  readonly rsmDelayPaymentToggle: Locator = this.page.locator(`//span[contains(@aria-describedby,"DelayPayment")][@class="toggle-box"]`);  readonly shippingDateRequested: Locator = this.page.locator(`[data-dyn-controlname="SalesTable_ShippingDateRequested"]`);
  readonly dlvTerm: Locator = this.page.locator(`[data-dyn-controlname="DeliveryAddition_DlvTerm"]`);
  readonly oK: Locator = this.page.locator(`[data-dyn-controlname="OK"][name="OK"]`);
  readonly itemId: Locator = this.page.locator(`input[aria-label="Item number"][role="combobox"]`);
  readonly div1773346990910: Locator = this.page.locator(`div.ScrollbarLayout_face.ScrollbarLayout_faceHorizontal.public_Scrollbar_faceActive`);
  readonly salesQty: Locator = this.page.locator(`input[aria-label="Quantity"]`);
  readonly headerViewHeader: Locator = this.page.locator(`[data-dyn-controlname="HeaderView_header"]`);
  readonly rsmHeaderShipmentWindowRsmShippingStartDate: Locator = this.page.locator(`[data-dyn-controlname="rsmHeaderShipmentWindow_rsmShippingStartDate"]`);
  readonly rsmHeaderShipmentWindowRsmShippingEndDate: Locator = this.page.locator(`[data-dyn-controlname="rsmHeaderShipmentWindow_rsmShippingEndDate"]`);
  readonly yes: Locator = this.page.locator(`[data-dyn-controlname="Yes"][name="Yes"]`);
  readonly complete: Locator = this.page.locator(`[data-dyn-controlname="Complete"][name="Complete"]`);
  readonly addBtn: Locator = this.page.locator(`[data-dyn-controlname="AddBtn"][name="AddBtn"]`);
  readonly identificationTenderTypeId: Locator = this.page.locator(`[data-dyn-controlname="Identification_TenderTypeId"]`);
  readonly oKButton: Locator = this.page.locator(`[data-dyn-controlname="OKButton"][name="OKButton"]`);
  readonly submitButton: Locator = this.page.locator(`[data-dyn-controlname="SubmitButton"][name="SubmitButton"]`);
  // readonly submitButton: Locator = this.page.locator(`[data-dyn-form-name="MCRSalesOrderRecap"] [data-dyn-controlname="SubmitButton"]`);
  readonly salesOrder: Locator = this.page.locator(`[data-dyn-form-name="SalesTable"] [data-dyn-controlname="SalesOrder"]`);
  readonly buttonCreateDropShipment: Locator = this.page.locator(`[data-dyn-controlname="buttonCreateDropShipment"][name="buttonCreateDropShipment"]`);
  readonly chkIncluded: Locator = this.page.locator(`[data-dyn-controlname="ChkIncluded"][data-dyn-focus="[role='checkbox']"] rect`);
  readonly commandButtonOK: Locator = this.page.locator(`[data-dyn-controlname="CommandButtonOK"][name="CommandButtonOK"]`);
  readonly general: Locator = this.page.locator(`[data-dyn-form-name="SalesTable"] [data-dyn-controlname="General"]`);
  readonly buttonReferences: Locator = this.page.locator(`[data-dyn-controlname="buttonReferences"][name="buttonReferences"]`);
  readonly okButton: Locator = this.page.locator(`[data-dyn-controlname="OkButton"][name="OkButton"]`);
  readonly buttonPurchTable: Locator = this.page.locator(`[data-dyn-controlname="buttonPurchTable"][name="buttonPurchTable"]`);
  readonly creditLimitYes: Locator = this.page.locator(`[data-dyn-form-name="SysBoxForm"] button:has-text("Yes")`);

  // --- assertion locators ----------------------------------------------------------
  readonly soHeaderTitle: Locator = this.page.locator(`span[id*="SalesTable_"][data-dyn-controlname="HeaderTitle"]`);
  readonly poHeaderTitle: Locator = this.page.locator(`span[id*="PurchTable_"][data-dyn-controlname="HeaderTitle"]`);
  readonly purchId: Locator = this.page.locator(`input[aria-label="Purchase order"]`); // Assert: visible | op: truthy

  //----payment fallback if submit button is not working---------
  readonly paymGridTenderTypeId: Locator = this.page.locator(`//input[contains(@id,"PaymGrid_TenderTypeId")]`);
  readonly removePaymBtn: Locator = this.page.locator(`//span[contains(@id,"RemovePaymBtn")][@class="button-label"]`);
  readonly removeConfirmYes: Locator = this.page.locator(`//span[contains(@id,"SysBoxForm")][contains(text(),"Yes")]`);
  readonly salesTotal: Locator = this.page.locator(`//input[contains(@id,"SalesTotal")]`);
  readonly identificationAmount: Locator = this.page.locator(`//input[contains(@id,"Identification_Amount")]`);


  async clickSearch(): Promise<void> {
    // No-op: navSearch (in the adjacent fill step) handles this atomically.
  }

  async fillSearchBox(value: string): Promise<void> {
    // Atomic D365 global search: open overlay → type → wait for result → click.
    // Must stay in one call — the nav overlay closes on any blur/focus event.
    await this.navSearch(value, this.allSalesOrders);
  }

  async clickAllSalesOrders(): Promise<void> {
    // No-op: navSearch (in the adjacent fill step) handles this atomically.
  }

  async clickNewButton(): Promise<void> {
    await this.safeClick(this.newButton);
    await this.waitForProcessing();
  }

  async fillCustAccount(value: string): Promise<void> {
    await this.safeFill(this.custAccount, value);
    await this.waitForProcessing();
  }

  async clickRsmDelayPayment(): Promise<void> {
    await this.page.waitForTimeout(3000); // Wait for 3 seconds
    await this.rsmDelayPaymentToggle.waitFor({ state: 'visible', timeout: 30000 });
    const ariaChecked = await this.rsmDelayPaymentToggle.getAttribute("aria-checked");
    if (ariaChecked === "true") {
      await this.safeClick(this.rsmDelayPaymentToggle);
      await this.waitForProcessing();
    }
    // already "false" → skip
  }

  async clickShippingDateRequested(): Promise<void> {
    await this.safeClick(this.shippingDateRequested);
    await this.waitForProcessing();
  }

  async fillShippingDateRequested(value: string): Promise<void> {
    await this.safeFill(this.shippingDateRequested, this.validateAndFormatDate("shippingDateRequested", value));
    await this.waitForProcessing();
  }
  async fillDlvTerm(value: string): Promise<void> {
    await this.safeFill(this.dlvTerm, value);
    await this.waitForProcessing();
  }
  async clickOK(): Promise<void> {
    await this.safeClick(this.oK);
    await this.waitForProcessing();
  }

  async fillItemId(value: string): Promise<void> {
    await this.safeFill(this.itemId, value);
    await this.waitForProcessing();
  }

  async fillSalesQty(value: string): Promise<void> {
    await this.safeFill(this.salesQty, value);
    await this.waitForProcessing();
  }

  async clickHeaderViewHeader(): Promise<void> {
    await this.safeClick(this.headerViewHeader);
    await this.waitForProcessing();
  }

  async fillRsmHeaderShipmentWindowRsmShippingStartDate(value: string): Promise<void> {
    await this.safeFill(this.rsmHeaderShipmentWindowRsmShippingStartDate, this.validateAndFormatDate("rsmHeaderShipmentWindowRsmShippingStartDate", value));
    await this.waitForProcessing();
  }

  async fillRsmHeaderShipmentWindowRsmShippingEndDate(value: string): Promise<void> {
    await this.safeFill(this.rsmHeaderShipmentWindowRsmShippingEndDate, this.validateAndFormatDate("rsmHeaderShipmentWindowRsmShippingEndDate", value));
    await this.waitForProcessing();
  }

  async clickYes(): Promise<void> {
    await this.safeClick(this.yes);
    await this.waitForProcessing();
  }

  async fillRsmHeaderShipmentWindowRsmShippingEndDate2(value: string): Promise<void> {
    await this.safeFill(this.rsmHeaderShipmentWindowRsmShippingEndDate, this.validateAndFormatDate("rsmHeaderShipmentWindowRsmShippingEndDate", value));
    await this.waitForProcessing();
  }

  async clickComplete(): Promise<void> {
    await this.safeClick(this.complete);
    await this.waitForProcessing();
  }

  async clickYes2(): Promise<void> {
    await this.safeClick(this.yes);
    await this.waitForProcessing();
  }

  async clickAddBtn(): Promise<void> {
    await this.safeClick(this.addBtn);
    await this.waitForProcessing();
    await this.page.waitForTimeout(2000); // Wait for 2 seconds
  }

  async fillIdentificationTenderTypeId(value: string): Promise<void> {
    const input = this.identificationTenderTypeId.locator('input').first();
    await input.click();
    await input.pressSequentially(value, { delay: 150 });
    await this.waitForLookupOptionsStable();
    await this.page.waitForTimeout(3000);
    await input.press('Enter');
    await this.waitForProcessing();
  }

  async clickOKButton(): Promise<void> {
    await this.safeClick(this.oKButton);
    await this.waitForProcessing();
    // Handle optional credit limit exceeded popup
    const isVisible = await this.creditLimitYes.isVisible().catch(() => false);
    if (isVisible) {
      await this.safeClick(this.creditLimitYes);
      await this.page.waitForTimeout(3000);
      await this.waitForProcessing();
    }
  }

  // async clickSubmitButton(): Promise<void> {
  //   await this.safeClick(this.submitButton);
  //   await this.waitForProcessing();
  // }

  async clickSubmitButton(): Promise<void> {
    await this.safeClick(this.submitButton);
    await this.waitForProcessing();

    // ── Fallback logic ──────────────────────────────────────────────────────
    // If MCRSalesOrderRecap dialog is still open after Submit, it means the
    // payment method "3" was rejected. Fallback: remove existing payment,
    // re-add with method "2" (Customer Account) using the full sales total,
    // then retry Submit.
    const isStillOpen = await this.page.locator(`[data-dyn-form-name="MCRSalesOrderRecap"]`)
      .isVisible().catch(() => false);

    if (isStillOpen) {
      // Step 1 — select existing payment row and remove it
      await this.safeClick(this.paymGridTenderTypeId);
      await this.waitForProcessing();
      await this.safeClick(this.removePaymBtn);
      await this.waitForProcessing();
      // Confirm removal popup
      const removeYes = this.page.locator(`//span[contains(@id,"SysBoxForm")][contains(text(),"Yes")]`);
      await this.safeClick(removeYes);
      await this.waitForProcessing();
      // Step 2 — capture the sales total amount
      const salesTotalValue = await this.salesTotal.inputValue();
      console.log(`📋 Captured Sales Total: ${salesTotalValue}`);

      // Step 3 — add new payment with method "2" using same approach as tender type "3"
      await this.safeClick(this.addBtn);
      await this.waitForProcessing();
      const paymDialogInput = this.page.locator(`[data-dyn-form-name="MCRCustPaymDialog"] [data-dyn-controlname="Identification_TenderTypeId"]`).locator('input').first();
      await paymDialogInput.click();
      await paymDialogInput.pressSequentially('2', { delay: 150 });
      await this.waitForLookupOptionsStable();
      await this.page.waitForTimeout(3000);
      await paymDialogInput.press('Enter');
      await this.waitForProcessing();

      // Step 4 — clean and enter captured sales total in amount field
      // Sales total may contain commas e.g. "124,072.50" — strip before filling
      const amountField = this.page.locator(`[data-dyn-form-name="MCRCustPaymDialog"] [data-dyn-controlname="Identification_Amount"]`);
      const cleanAmount = salesTotalValue.replace(/,/g, '');
      await this.safeFill(amountField, cleanAmount);
      await this.waitForProcessing();

      // Step 5 — confirm and retry Submit
      await this.safeClick(this.oKButton);
      await this.waitForProcessing();
      await this.safeClick(this.submitButton);
      await this.waitForProcessing();
    }
  }
  async clickSalesOrder(): Promise<void> {
    await this.safeClick(this.salesOrder);
    await this.waitForProcessing();
  }

  async clickButtonCreateDropShipment(): Promise<void> {
    await this.safeClick(this.buttonCreateDropShipment);
    await this.waitForProcessing();
  }

  async clickChkIncluded(): Promise<void> {
    await this.chkIncluded.first().waitFor({ state: 'visible', timeout: 30000 });
    const count = await this.chkIncluded.count();
    for (let i = 0; i < count; i++) {
      await this.chkIncluded.nth(i).click();
      await this.waitForProcessing();
    }
  }

  async clickCommandButtonOK(): Promise<void> {
    await this.safeClick(this.commandButtonOK);
    await this.waitForProcessing();
  }

  async clickGeneral(): Promise<void> {
    await this.safeClick(this.general);
    await this.waitForProcessing();
  }

  async clickButtonReferences(): Promise<void> {
    await this.safeClick(this.buttonReferences);
    await this.waitForProcessing();
  }

  async clickOkButton(): Promise<void> {
    await this.safeClick(this.okButton);
    await this.waitForProcessing();
  }

  async clickButtonPurchTable(): Promise<void> {
    await this.safeClick(this.buttonPurchTable);
    await this.waitForProcessing();
  }

  // ─── assert Header Title [visible/truthy] ─────────────────────────────────
  // expected: SO000235232 : Matter Brothers (d-Channel)
  async assertHeaderTitleVisible(): Promise<void> {
    const soTitle = this.page.locator(`span[id*="SalesTable_"][data-dyn-controlname="HeaderTitle"]`).first();
    await soTitle.waitFor({ state: 'attached', timeout: 30000 });
    const text = (await soTitle.textContent()) ?? '';
    const soNumber = text.split(':')[0].trim(); // extracts e.g. "SO000235308"
    this.collectedResults['salesOrderId'] = soNumber;
    console.log(`📋 SO Header Title: ${text.trim()}`);
    console.log(`📋 SO Header Title: ${text.trim()}`);
  }

  // ─── assert Purch Table_ Purch Id [visible/truthy] ─────────────────────────────────
  // expected: PO317685
  async assertPurchIdVisible(): Promise<void> {
    await this.softAssertVisible("purchId", this.purchId);
    await this.captureInputValueWithRetry("expectedPurchId", this.purchId).catch(() => {});
  }

  // ─── assert Header Title [visible/truthy] ─────────────────────────────────
  // expected: PO317685 : 9417 - Tangshan Xiangyu Furniture Co Ltd
  async assertHeaderTitle1Visible(): Promise<void> {
    const poTitle = this.page.locator(`span[id*="PurchTable_"][data-dyn-controlname="HeaderTitle"]`).first();
    await poTitle.waitFor({ state: 'visible', timeout: 30000 });
    const text = (await poTitle.textContent()) ?? '';
    const capturedPO = String(this.collectedResults['expectedPurchId'] ?? '');
    if (capturedPO && !text.includes(capturedPO)) {
      throw new Error(`❌ PO Header mismatch. Expected to contain: ${capturedPO}, Found: ${text}`);
    }
    this.collectedResults['capturedPOTitle'] = text.trim();
    console.log(`✅ PO Header verified and captured: ${text.trim()}`);
  }
}
