import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  // Recording...

  ;await page.goto('https://fourhands-test.sandbox.operations.dynamics.com/?cmp=FH&mi=DefaultDashboard');

  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search for a page' }).fill('all sales order');
  await page.locator('#NavigationSearchBox_listbox_item0').getByText('All sales orders').click();
  await page.getByRole('button', { name: ' New' }).click();
  await page.getByRole('combobox', { name: 'Customer account' }).fill('100001');
  await page.getByRole('combobox', { name: 'Customer account' }).press('Tab');
  await page.locator('#SalesCreateOrder_8_SalesTable_DlvMode > .lookupDock-buttonContainer > .lookupButton').click();
  await page.getByRole('combobox', { name: 'Mode of delivery' }).click();
  await page.getByRole('combobox', { name: 'Mode of delivery' }).fill('aews-b2b');
  await page.getByRole('combobox', { name: 'Mode of delivery' }).press('Enter');
  await page.goto('https://fourhands-test.sandbox.operations.dynamics.com/?cmp=FH&mi=SalesTableListPage');
  await page.getByRole('combobox', { name: 'Item number' }).click();
  await page.getByRole('combobox', { name: 'Item number' }).fill('100054-009');
  await page.getByRole('combobox', { name: 'Item number' }).press('Enter');
  await page.getByText('Header', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Delivery terms' }).click();
  await page.getByRole('combobox', { name: 'Delivery terms PREPAID Click' }).fill('third-party');
  await page.getByRole('combobox', { name: 'Delivery terms PREPAID Click' }).press('Tab');
  await page.getByRole('combobox', { name: 'Delivery terms' }).click();
  await page.locator('#SalesTable_7_Delivery_DlvTerm > .lookupDock-buttonContainer > .lookupButton').click();
  await page.getByRole('combobox', { name: 'Delivery terms' }).click();
  await page.getByRole('combobox', { name: 'Delivery terms' }).fill('');
  await page.locator('#SalesTable_7_Delivery_DlvTerm > .lookupDock-buttonContainer > .lookupButton').click();
  await page.locator('#Sel_4975_0_17_input').click();
  await page.getByText('Lines', { exact: true }).click();
  await page.getByRole('tabpanel', { name: 'Lines' }).getByLabel('More').click();
  await page.getByRole('button', { name: 'Inventory ' }).click();
  await page.getByRole('switch', { name: 'Update Delivery terms' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('menuitem', { name: 'Reservation', exact: true }).click();
  await page.getByRole('button', { name: 'Reserve lot' }).click();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByRole('button', { name: 'Complete' }).click();
  await expect(page.getByRole('textbox', { name: 'Balance' })).toBeVisible();
  await page.getByRole('button', { name: ' Add', exact: true }).click();
  await page.locator('#MCRCustPaymDialog_16_Identification_TenderTypeId > .lookupDock-buttonContainer > .lookupButton').click();
  await page.getByTitle('Customer Account', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Sell' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await expect(page.locator('#SalesTable_7_HeaderTitle')).toContainText('SO000235029 : Nicole Roby Designs');
  await expect(page.getByText('SO000235029
  await page.getByRole('button', { name: ' Filter' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.getByRole('gridcell', { name: 'SO000235028' }).getByLabel('Criteria').click();
  await page.getByRole('gridcell', { name: 'SO000235028' }).getByLabel('Criteria').press('ArrowRight');
  await page.getByRole('combobox', { name: 'Criteria' }).fill('SO000235029');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search for a page' }).fill('candidate for shipping orders');
  await page.getByRole('textbox', { name: 'Search for a page' }).press('Enter');
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('checkbox', { name: 'Select or unselect row' }).click();
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search for a page' }).fill('grouping');
  await page.getByRole('textbox', { name: 'Search for a page' }).press('Enter');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search for a page' }).fill('shipment builder');
  await page.getByRole('textbox', { name: 'Search for a page' }).press('Enter');
  await page.locator('#rsmShipmentGroup_ShipmentGroupId_6253_0_header').getByText('Shipment group').click();
  await page.getByRole('button', { name: ' Sort Z to A' }).click();
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search for a page' }).fill('all sales order');
  await page.getByRole('textbox', { name: 'Search for a page' }).press('Enter');
  await page.locator('#SalesTable_SalesIdAdvanced_7068_0_160_input').click();
  await page.locator('#SalesTable_SalesIdAdvanced_7068_0_224_input').click();
  await page.getByRole('textbox', { name: 'Sales order' }).click();
  await page.getByRole('textbox', { name: 'Sales order' }).click(); : Nicole Roby')).toBeVisible();
  await page.getByRole('textbox', { name: 'Search for a page' }).click();
  await page.getByRole('textbox', { name: 'Search for a page' }).fill('candidate for shipping');
  await page.getByRole('textbox', { name: 'Search for a page' }).press('Enter');
  await page.getByRole('button', { name: 'Records to include' }).click();
  await page.goto('https://fourhands-test.sandbox.operations.dynamics.com/?cmp=FH&mi=SalesTableDetails');
  await page.locator('div:nth-child(2) > div > .ScrollbarLayout_main > .ScrollbarLayout_face').click();
  await page.locator('.ScrollbarLayout_main.ScrollbarLayout_mainHorizontal.public_Scrollbar_main.public_Scrollbar_mainOpaque.public_Scrollbar_mainActive').click();
  await page.locator('.ScrollbarLayout_main.ScrollbarLayout_mainHorizontal.public_Scrollbar_main.public_Scrollbar_mainOpaque.public_Scrollbar_mainActive').click();
  await page.locator('.ScrollbarLayout_main.ScrollbarLayout_mainHorizontal.public_Scrollbar_main.public_Scrollbar_mainOpaque.public_Scrollbar_mainActive').click();
  await page.locator('.ScrollbarLayout_face.ScrollbarLayout_faceHorizontal.public_Scrollbar_faceActive').click();
  await page.getByRole('grid', { name: 'Order lines' }).getByLabel('Shipment group').click(); //this is the shipment number  under the lines. after grouping. 

  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search for a page' }).fill('shipment builder');
  await page.getByRole('textbox', { name: 'Search for a page' }).press('Enter');
  await page.getByRole('combobox', { name: 'Filter' }).click();
  await page.getByRole('textbox', { name: 'Filter' }).fill('GRP000260521');
  await page.getByRole('combobox', { name: 'Filter' }).press('Enter');
  await page.getByRole('textbox', { name: 'Shipment group' }).click();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByRole('textbox', { name: 'Shipment group' }).click();
  await page.getByRole('button', { name: 'Shipments' }).click();
  await page.getByRole('button', { name: 'Create shipment' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.goto('https://fourhands-test.sandbox.operations.dynamics.com/?cmp=FH&mi=rsmShipmentBuilder');
  await page.locator('#Grid_11065_0_grid > .public_fixedDataTable_horizontalScrollbar > div > .ScrollbarLayout_main > .ScrollbarLayout_face').click();
  await page.locator('.ScrollbarLayout_face.ScrollbarLayout_faceHorizontal.public_Scrollbar_faceActive').click();
  await page.locator('.ScrollbarLayout_main.ScrollbarLayout_mainHorizontal.public_Scrollbar_main.public_Scrollbar_mainOpaque.public_Scrollbar_mainActive').click();
  await page.getByRole('textbox', { name: 'Koerber status' }).click(); // this is where the koerber status is visible in the shipment builder after creating the shipment, if it says released after 20 mins it shows up in koerber. 
  await page.getByRole('button', { name: ' Stop' }).click();
  await page.getByRole('link', { name: ' Save to this PC' }).click();
  await page.getByRole('textbox', { name: 'Payment status' }).click(); // once payment status is submitted, the sales order is ready for shipment.
