import { Page, Locator, expect } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * PODchannelPage -- Auto-generated by Smart Recorder v3.0
 * Platform: D365 | Flow: PO_D_channel
 * Generated: 2026-03-12T20:28:58.199Z
 * Session: sessions/podchannel_session.json
 *
 * To regenerate: npx ts-node converter.ts sessions/podchannel_session.json
 * To edit & regenerate: npx ts-node converter.ts sessions/podchannel_session.json --edit
 */
export class PODchannelPage extends BasePage {

  constructor(page: Page) {
    super(page, page.context());
  }

  // --- locators -------------------------------------------------------------------
  readonly search: Locator = this.page.locator(`button[aria-label="Search"]`);
  readonly searchBox: Locator = this.page.locator(`input[aria-label="Search for a page"]`);
  readonly allSalesOrders: Locator = this.page.locator(`span:has-text("All sales orders")`);
  readonly newButton: Locator = this.page.locator(`[data-dyn-controlname="SystemDefinedNewButton"][name="SystemDefinedNewButton"]`);
  readonly custAccount: Locator = this.page.locator(`[data-dyn-controlname="SalesTable_CustAccount"]`);
  readonly rsmDelayPayment: Locator = this.page.locator(`[data-dyn-controlname="SalesTable_rsmDelayPayment"]`);
  readonly shippingDateRequested: Locator = this.page.locator(`[data-dyn-controlname="SalesTable_ShippingDateRequested"]`);
  readonly oK: Locator = this.page.locator(`[data-dyn-controlname="OK"][name="OK"]`);
  readonly itemId: Locator = this.page.locator(`input[aria-label="Item number"]`);
  readonly div1773346990910: Locator = this.page.locator(`div.ScrollbarLayout_face.ScrollbarLayout_faceHorizontal.public_Scrollbar_faceActive`);
  readonly salesQty: Locator = this.page.locator(`input[aria-label="Quantity"]`);
  readonly headerViewHeader: Locator = this.page.locator(`[data-dyn-controlname="HeaderView_header"]`);
  readonly rsmHeaderShipmentWindowRsmShippingStartDate: Locator = this.page.locator(`[data-dyn-controlname="rsmHeaderShipmentWindow_rsmShippingStartDate"]`);
  readonly rsmHeaderShipmentWindowRsmShippingEndDate: Locator = this.page.locator(`[data-dyn-controlname="rsmHeaderShipmentWindow_rsmShippingEndDate"]`);
  readonly yes: Locator = this.page.locator(`[data-dyn-controlname="Yes"][name="Yes"]`);
  readonly complete: Locator = this.page.locator(`[data-dyn-controlname="Complete"][name="Complete"]`);
  readonly addBtn: Locator = this.page.locator(`[data-dyn-controlname="AddBtn"][name="AddBtn"]`);
  readonly identificationTenderTypeId: Locator = this.page.locator(`[data-dyn-controlname="Identification_TenderTypeId"]`);
  readonly oKButton: Locator = this.page.locator(`[data-dyn-controlname="OKButton"][name="OKButton"]`);
  readonly submitButton: Locator = this.page.locator(`[data-dyn-controlname="SubmitButton"][name="SubmitButton"]`);
  readonly salesOrder: Locator = this.page.locator(`[data-dyn-form-name="SalesTable"] [data-dyn-controlname="SalesOrder"]`);
  readonly buttonCreateDropShipment: Locator = this.page.locator(`[data-dyn-controlname="buttonCreateDropShipment"][name="buttonCreateDropShipment"]`);
  readonly rect1773347247383: Locator = this.page.locator(`:has([data-dyn-controlname="Field"] input[value="No"]) //rect`);
  readonly commandButtonOK: Locator = this.page.locator(`[data-dyn-controlname="CommandButtonOK"][name="CommandButtonOK"]`);
  readonly general: Locator = this.page.locator(`[data-dyn-form-name="SalesTable"] [data-dyn-controlname="General"]`);
  readonly buttonReferences: Locator = this.page.locator(`[data-dyn-controlname="buttonReferences"][name="buttonReferences"]`);
  readonly okButton: Locator = this.page.locator(`[data-dyn-controlname="OkButton"][name="OkButton"]`);
  readonly buttonPurchTable: Locator = this.page.locator(`[data-dyn-controlname="buttonPurchTable"][name="buttonPurchTable"]`);

  // --- assertion locators ----------------------------------------------------------
  readonly headerTitle: Locator = this.page.locator(`[data-dyn-controlname="HeaderTitle"]`); // Assert: visible | op: truthy
  readonly purchId: Locator = this.page.locator(`input[aria-label="Purchase order"]`); // Assert: visible | op: truthy



  async clickSearch(): Promise<void> {
    // No-op: navSearch (in the adjacent fill step) handles this atomically.
  }

  async fillSearchBox(value: string): Promise<void> {
    // Atomic D365 global search: open overlay → type → wait for result → click.
    // Must stay in one call — the nav overlay closes on any blur/focus event.
    await this.navSearch(value, this.allSalesOrders);
  }

  async clickAllSalesOrders(): Promise<void> {
    // No-op: navSearch (in the adjacent fill step) handles this atomically.
  }

  async clickNewButton(): Promise<void> {
    await this.safeClick(this.newButton);
    await this.waitForProcessing();
  }

  async fillCustAccount(value: string): Promise<void> {
    await this.safeFill(this.custAccount, value);
    await this.waitForProcessing();
  }

  async clickRsmDelayPayment(): Promise<void> {
    await this.safeClick(this.rsmDelayPayment);
    await this.waitForProcessing();
  }

  async clickShippingDateRequested(): Promise<void> {
    await this.safeClick(this.shippingDateRequested);
    await this.waitForProcessing();
  }

  async fillShippingDateRequested(value: string): Promise<void> {
    await this.safeFill(this.shippingDateRequested, this.validateAndFormatDate("shippingDateRequested", value));
    await this.waitForProcessing();
  }

  async clickOK(): Promise<void> {
    await this.safeClick(this.oK);
    await this.waitForProcessing();
  }

  async fillItemId(value: string): Promise<void> {
    await this.safeFill(this.itemId, value);
    await this.waitForProcessing();
  }

  async clickDiv1773346990910(): Promise<void> {
    await this.safeClick(this.div1773346990910);
    await this.waitForProcessing();
  }

  async fillSalesQty(value: string): Promise<void> {
    await this.safeFill(this.salesQty, value);
    await this.waitForProcessing();
  }

  async clickHeaderViewHeader(): Promise<void> {
    await this.safeClick(this.headerViewHeader);
    await this.waitForProcessing();
  }

  async fillRsmHeaderShipmentWindowRsmShippingStartDate(value: string): Promise<void> {
    await this.safeFill(this.rsmHeaderShipmentWindowRsmShippingStartDate, this.validateAndFormatDate("rsmHeaderShipmentWindowRsmShippingStartDate", value));
    await this.waitForProcessing();
  }

  async fillRsmHeaderShipmentWindowRsmShippingEndDate(value: string): Promise<void> {
    await this.safeFill(this.rsmHeaderShipmentWindowRsmShippingEndDate, this.validateAndFormatDate("rsmHeaderShipmentWindowRsmShippingEndDate", value));
    await this.waitForProcessing();
  }

  async clickYes(): Promise<void> {
    await this.safeClick(this.yes);
    await this.waitForProcessing();
  }

  async fillRsmHeaderShipmentWindowRsmShippingEndDate2(value: string): Promise<void> {
    await this.safeFill(this.rsmHeaderShipmentWindowRsmShippingEndDate, this.validateAndFormatDate("rsmHeaderShipmentWindowRsmShippingEndDate", value));
    await this.waitForProcessing();
  }

  async clickComplete(): Promise<void> {
    await this.safeClick(this.complete);
    await this.waitForProcessing();
  }

  async clickYes2(): Promise<void> {
    await this.safeClick(this.yes);
    await this.waitForProcessing();
  }

  async clickAddBtn(): Promise<void> {
    await this.safeClick(this.addBtn);
    await this.waitForProcessing();
  }

  async fillIdentificationTenderTypeId(value: string): Promise<void> {
    await this.safeFill(this.identificationTenderTypeId, value);
    await this.waitForProcessing();
  }

  async clickOKButton(): Promise<void> {
    await this.safeClick(this.oKButton);
    await this.waitForProcessing();
  }

  async clickSubmitButton(): Promise<void> {
    await this.safeClick(this.submitButton);
    await this.waitForProcessing();
  }

  async clickSalesOrder(): Promise<void> {
    await this.safeClick(this.salesOrder);
    await this.waitForProcessing();
  }

  async clickButtonCreateDropShipment(): Promise<void> {
    await this.safeClick(this.buttonCreateDropShipment);
    await this.waitForProcessing();
  }

  async clickRect1773347247383(): Promise<void> {
    await this.safeClick(this.rect1773347247383);
    await this.waitForProcessing();
  }

  async clickCommandButtonOK(): Promise<void> {
    await this.safeClick(this.commandButtonOK);
    await this.waitForProcessing();
  }

  async clickGeneral(): Promise<void> {
    await this.safeClick(this.general);
    await this.waitForProcessing();
  }

  async clickButtonReferences(): Promise<void> {
    await this.safeClick(this.buttonReferences);
    await this.waitForProcessing();
  }

  async clickOkButton(): Promise<void> {
    await this.safeClick(this.okButton);
    await this.waitForProcessing();
  }

  async clickButtonPurchTable(): Promise<void> {
    await this.safeClick(this.buttonPurchTable);
    await this.waitForProcessing();
  }

  // ─── assert Header Title [visible/truthy] ─────────────────────────────────
  // expected: SO000235232 : Matter Brothers (d-Channel)
  async assertHeaderTitleVisible(): Promise<void> {
    await expect(async () => {
      await expect(this.headerTitle).toBeVisible();
    }).toPass({ timeout: 30000 });
  }

  // ─── assert Purch Table_ Purch Id [visible/truthy] ─────────────────────────────────
  // expected: PO317685
  async assertPurchIdVisible(): Promise<void> {
    await this.softAssertVisible("purchId", this.purchId);
    await this.captureInputValueWithRetry("expectedPurchId", this.purchId).catch(() => {});
  }

  // ─── assert Header Title [visible/truthy] ─────────────────────────────────
  // expected: PO317685 : 9417 - Tangshan Xiangyu Furniture Co Ltd
  async assertHeaderTitle1Visible(): Promise<void> {
    await expect(async () => {
      await expect(this.headerTitle).toBeVisible();
    }).toPass({ timeout: 30000 });
  }
}
